/**
 * \file
 *
 * \brief AVR XMEGA EDMA example 1
 *
 * Copyright (c) 2014-2015 Atmel Corporation. All rights reserved.
 *
 * \asf_license_start
 *
 * \page License
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * 1. Redistributions of source code must retain the above copyright notice,
 *    this list of conditions and the following disclaimer.
 *
 * 2. Redistributions in binary form must reproduce the above copyright notice,
 *    this list of conditions and the following disclaimer in the documentation
 *    and/or other materials provided with the distribution.
 *
 * 3. The name of Atmel may not be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * 4. This software may only be redistributed and used in connection with an
 *    Atmel microcontroller product.
 *
 * THIS SOFTWARE IS PROVIDED BY ATMEL "AS IS" AND ANY EXPRESS OR IMPLIED
 * WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT ARE
 * EXPRESSLY AND SPECIFICALLY DISCLAIMED. IN NO EVENT SHALL ATMEL BE LIABLE FOR
 * ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
 * OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
 * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
 * STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * \asf_license_stop
 *
 */

/**
 * \mainpage
 *
 * \section intro Introduction
 * This simple example shows how to use the \ref edma_group.
 *
 * \section files Main Files
 * - edma_example_1.c example application
 * - conf_example.h example configuration
 *
 * \section device_info Device Info
 * All AVR XMEGA devices with a EDMA controller can be used. This example have
 * been tested on the following board(s):
 * - XMEGA-E5-XPLAINED
 *
 * \section description Description of the example
 *
 * This example will start a EDMA transfer between two internal memory areas,
 * and upon completion it will verify this by comparing those areas.
 *
 * During the progress of the application it will output some information to
 * the LCD screen, and the number displayed have the following assignment:
 * - <b>0</b>: EDMA have been started
 * - <b>1</b>: EDMA completed successfully
 * - <b>2</b>: CPU verified EDMA transfer to be correct
 * - <b>3</b>: CPU verified that source haven't been garbled
 * - <b>5</b>: EDMA transfer ended in failure
 * - <b>6</b>: CPU verification of EDMA transfer failed
 * - <b>7</b>: CPU verification of source failed
 *
 * In a successful operation <b>1</b>, <b>2</b> and <b>3</b> should display in
 * sequence, and on fault <b>5</b>, <b>6</b> or <b>7</b> will replace <b>1</b>,
 * <b>2</b> and <b>3</b>, respectively within the sequence. Automatically, the
 * example program will give a status, <b>OK</b> or <b>Error</b>.
 *
 * \section dependencies Dependencies
 * This example depends on the following modules:
 * - \ref edma_group
 * - \ref pmic_group for interrupt handling
 * - \ref gfx_mono for display
 *
 * \section compinfo Compilation info
 * This software was written for the GNU GCC and IAR for AVR. Other compilers
 * may or may not work.
 *
 * \section contactinfo Contact Information
 * For further information, visit <a href="http://www.atmel.com/">Atmel</a>.\n
 */
/*
 * Support and FAQ: visit <a href="http://www.atmel.com/design-support/">Atmel Support</a>
 */
#include <conf_example.h>
#include <string.h>
#include <asf.h>

/** \brief Source buffer to use for EDMA transfer */
static uint8_t source[EDMA_BUFFER_SIZE];

/** \brief Destination buffer to use for EDMA transfer */
static uint8_t destination[EDMA_BUFFER_SIZE];

/** \brief Error counter */
static volatile uint8_t err_cnt = 0;

/**
 * \brief Fill buffer with a specific pattern
 *
 * \param buffer Buffer to fill with a specific pattern
 * \param len Length of the buffer
 */
static void fill_pattern(uint8_t *buffer, size_t len)
{
	int i;

	for (i = 0; i < len; i++) {
		buffer[i] = 42 ^ (i & 0xff) ^ (i >> 8);
	}
}

/**
 * \brief Verify if buffer if filled by the specific pattern generated by the
 * fill_pattern() function.
 *
 * \param buffer Buffer to verify
 * \param len Length of the buffer
 *
 * \retval true Buffer is equal to specific pattern
 * \retval false Buffer is not equal to specific pattern
 */
static bool verify_pattern(uint8_t *buffer, size_t len)
{
	for (size_t i = 0; i < len; i++) {
		if (buffer[i] != (42 ^ (i & 0xff) ^ (i >> 8))) {
			return false;
		}
	}

	return true;
}

/**
 * \brief Callback for EDMA transfer complete
 *
 * \param status Status of a completed (or failed) EDMA transfer
 */
static void example_edma_transfer_done(edma_channel_status_t status)
{
	/* Check EDMA transfer status */
	if (status == EDMA_CH_TRANSFER_COMPLETED) {
		gfx_mono_draw_string("1", 10, 16, &sysfont);
		err_cnt += 1;
	} else {
		gfx_mono_draw_string("5", 10, 16, &sysfont);
		err_cnt += 5;
	}

	/* Check if destination is as expected */
	if (verify_pattern(destination, EDMA_BUFFER_SIZE)) {
		gfx_mono_draw_string("2", 20, 16, &sysfont);
		err_cnt += 2;
	} else {
		gfx_mono_draw_string("6", 20, 16, &sysfont);
		err_cnt += 6;
	}

	/* Check if source haven't been garbled */
	if (verify_pattern(source, EDMA_BUFFER_SIZE)) {
		gfx_mono_draw_string("3", 30, 16, &sysfont);
		err_cnt += 3;
	} else {
		gfx_mono_draw_string("7", 30, 16, &sysfont);
		err_cnt += 7;
	}
}

/**
 * \brief main function
 */
int main(void)
{
	struct edma_channel_config my_ch_conf;

	/*
	 * Initialize basic features for the AVR XMEGA E family.
	 *  - PMIC is needed to enable all interrupt levels.
	 *  - Board init for setting up GPIO and board specific features.
	 *  - Sysclk init for configuring clock speed and turning of unused
	 *    peripherals.
	 *  - Sleepmgr init for setting up the basics for the sleep manager,
	 *    although not used in this example, but the sleep manager is used
	 *    by the DMA driver.
	 *  - Gfx_mono init for configuring the display controller and create a
	 *    framebuffer in RAM if the controller lacks two-way communication
	 */
	pmic_init();
	board_init();
	sysclk_init();
	sleepmgr_init();
	gfx_mono_init();

	/*
	 * Fill source buffer with a specific pattern and clear destination so
	 * we are sure they are different.
	 */
	fill_pattern(source, EDMA_BUFFER_SIZE);
	memset(destination, 0, EDMA_BUFFER_SIZE);

	edma_enable(EDMA_CHMODE);

	/*
	 * In this example the example_edma_transfer_done() function will be
	 * used as the callback function from completed EDMA block transfers.
	 * This function is called whenever an interrupt occurs on the EDMA
	 * channel this function is set to handle. A callback function is set
	 * by the edma_set_callback() function in the EDMA driver interface.
	 */
	edma_set_callback(EDMA_CHANNEL, example_edma_transfer_done);

	/* Make sure config is all zeroed out so we don't get any stray bits */
	memset(&my_ch_conf, 0, sizeof(my_ch_conf));

	/*
	 * This example will configure a EDMA channel with the following
	 * settings:
	 *  - Low interrupt priority
	 *  - 1 byte burst length
	 *  - EDMA_BUFFER_SIZE bytes for each transfer
	 *  - Reload source and destination address at end of each transfer
	 *  - Increment source and destination address during transfer
	 *  - Source address is set to \ref source
	 *  - Destination address is set to \ref destination
	 */
	edma_channel_set_interrupt_level(&my_ch_conf, EDMA_INT_LVL_LO);
	edma_channel_set_burst_length(&my_ch_conf, EDMA_CH_BURSTLEN_1BYTE_gc);
	edma_channel_set_transfer_count16(&my_ch_conf, EDMA_BUFFER_SIZE);
	edma_channel_set_src_reload_mode(&my_ch_conf,
			EDMA_CH_RELOAD_TRANSACTION_gc);
	edma_channel_set_dest_reload_mode(&my_ch_conf,
			EDMA_CH_RELOAD_TRANSACTION_gc);
	edma_channel_set_src_dir_mode(&my_ch_conf, EDMA_CH_DIR_INC_gc);
	edma_channel_set_dest_dir_mode(&my_ch_conf, EDMA_CH_DESTDIR_INC_gc);
	edma_channel_set_source_address(&my_ch_conf,
			(uint16_t)(uintptr_t)source);
	edma_channel_set_destination_address(&my_ch_conf,
			(uint16_t)(uintptr_t)destination);
	edma_channel_write_config(EDMA_CHANNEL, &my_ch_conf);

	/* Use the configuration above by enabling the EDMA channel in use. */
	edma_channel_enable(EDMA_CHANNEL);

	/*
	 * Enable interrupts as the example is now configured to handle them
	 * properly.
	 */
	cpu_irq_enable();

	/* Display text header. */
	gfx_mono_draw_string("EDMA ex-1:", 0, 0, &sysfont);

	/*
	 * Trigger a manual start since there is no trigger sources used in
	 * this example.
	 */
	edma_channel_trigger_block_transfer(EDMA_CHANNEL);

	/* Wait for the end of EDMA operation. */
	while (err_cnt == 0) {
		/*
		 * Force a NOP instruction for an eventual placement of a debug
		 * session breakpoint.
		 */
		asm ("nop\n");
	}

	/* Display the status of the EDMA operation. */
	if (err_cnt == 6) {
		gfx_mono_draw_string(" -> OK", 40, 16, &sysfont);
	} else {
		gfx_mono_draw_string(" -> Error", 40, 16, &sysfont);
	}

	while (true) {
		/*
		 * Force a NOP instruction for an eventual placement of a debug
		 * session breakpoint.
		 */
		asm ("nop\n");
	}
}
