/**
 * \file
 *
 * \brief Display organization for this application.
 *
 * Copyright (c) 2014-2018 Microchip Technology Inc. and its subsidiaries.
 *
 * \asf_license_start
 *
 * \page License
 *
 * Subject to your compliance with these terms, you may use Microchip
 * software and any derivatives exclusively with Microchip products.
 * It is your responsibility to comply with third party license terms applicable
 * to your use of third party software (including open source software) that
 * may accompany Microchip software.
 *
 * THIS SOFTWARE IS SUPPLIED BY MICROCHIP "AS IS". NO WARRANTIES,
 * WHETHER EXPRESS, IMPLIED OR STATUTORY, APPLY TO THIS SOFTWARE,
 * INCLUDING ANY IMPLIED WARRANTIES OF NON-INFRINGEMENT, MERCHANTABILITY,
 * AND FITNESS FOR A PARTICULAR PURPOSE. IN NO EVENT WILL MICROCHIP BE
 * LIABLE FOR ANY INDIRECT, SPECIAL, PUNITIVE, INCIDENTAL OR CONSEQUENTIAL
 * LOSS, DAMAGE, COST OR EXPENSE OF ANY KIND WHATSOEVER RELATED TO THE
 * SOFTWARE, HOWEVER CAUSED, EVEN IF MICROCHIP HAS BEEN ADVISED OF THE
 * POSSIBILITY OR THE DAMAGES ARE FORESEEABLE.  TO THE FULLEST EXTENT
 * ALLOWED BY LAW, MICROCHIP'S TOTAL LIABILITY ON ALL CLAIMS IN ANY WAY
 * RELATED TO THIS SOFTWARE WILL NOT EXCEED THE AMOUNT OF FEES, IF ANY,
 * THAT YOU HAVE PAID DIRECTLY TO MICROCHIP FOR THIS SOFTWARE.
 *
 * \asf_license_stop
 *
 */
/*
 * Support and FAQ: visit <a href="https://www.microchip.com/support/">Microchip Support</a>
 */
#ifndef CONF_APP_DISPLAY_H_INCLUDED
#define CONF_APP_DISPLAY_H_INCLUDED

#define DISPLAY_INTRO_ATMEL_DELAY           3000lu /* Unit ms */
#define DISPLAY_INTRO_MSG_EXIT              "SW1 to skip intro"
#define DISPLAY_INTRO_MSG_DELAY             7000lu /* Unit ms */
#define DISPLAY_INTRO_MSG_A                 "The demo gets light"
#define DISPLAY_INTRO_MSG_B                 "sensor and outputs"
#define DISPLAY_INTRO_MSG_C                 "them on DISP, USART"
#define DISPLAY_INTRO_HELP_DELAY            3000lu /* Unit ms */
#define DISPLAY_INTRO_HELP_A                "Quadrature encoder"
#define DISPLAY_INTRO_HELP_B                "changes sampling"

#define DISPLAY_CPU_LOAD_TEXT_POS_X         0
#define DISPLAY_CPU_LOAD_TEXT_POS_Y         0
#define DISPLAY_CPU_LOAD_TEXT               "CPU load"
#define DISPLAY_CPU_LOAD_PROBAR_START_POS_X DISPLAY_CPU_LOAD_TEXT_POS_X
#define DISPLAY_CPU_LOAD_PROBAR_START_POS_Y (DISPLAY_CPU_LOAD_TEXT_POS_Y + 9)
#define DISPLAY_CPU_LOAD_PROBAR_START_SIZE_X 1
#define DISPLAY_CPU_LOAD_PROBAR_START_SIZE_Y (DISPLAY_CPU_LOAD_PROBAR_SIZE_Y + 2)
#define DISPLAY_CPU_LOAD_PROBAR_STOP_POS_X  (DISPLAY_CPU_LOAD_TEXT_POS_X + DISPLAY_CPU_LOAD_PROBAR_MAX_SIZE_X +1)
#define DISPLAY_CPU_LOAD_PROBAR_STOP_POS_Y  DISPLAY_CPU_LOAD_PROBAR_START_POS_Y
#define DISPLAY_CPU_LOAD_PROBAR_STOP_SIZE_X 1
#define DISPLAY_CPU_LOAD_PROBAR_STOP_SIZE_Y (DISPLAY_CPU_LOAD_PROBAR_SIZE_Y + 2)
#define DISPLAY_CPU_LOAD_PROBAR_POS_X       (DISPLAY_CPU_LOAD_TEXT_POS_X + 1)
#define DISPLAY_CPU_LOAD_PROBAR_POS_Y       (DISPLAY_CPU_LOAD_TEXT_POS_Y + 11)
#define DISPLAY_CPU_LOAD_PROBAR_SIZE_Y      (4)
#define DISPLAY_CPU_LOAD_PROBAR_MAX_SIZE_X  (6 * 8)

#define DISPLAY_SAMPLING_TEXT_POS_X         ((128 / 2) + 3)
#define DISPLAY_SAMPLING_TEXT_POS_Y         0
#define DISPLAY_SAMPLING_TEXT               "Sampling\r\n%2u,%01us"
#define DISPLAY_SAMPLING_PROCIRCLE_POS_X    (DISPLAY_SAMPLING_TEXT_POS_X + 6 * 5 + 13)
#define DISPLAY_SAMPLING_PROCIRCLE_POS_Y    (DISPLAY_SAMPLING_TEXT_POS_Y + 9 + 5)
#define DISPLAY_SAMPLING_PROCIRCLE_RADIUS   (4)
#define DISPLAY_SAMPLING_PROCIRCLE_MAX_SIZE_X  (6 * 8)

#define DISPLAY_LIGHT_TEXT_POS_X            DISPLAY_SAMPLING_TEXT_POS_X
#define DISPLAY_LIGHT_TEXT_POS_Y            19
#define DISPLAY_LIGHT_TEXT                  "Light"
#define DISPLAY_LIGHT_PROBAR_START_POS_X    DISPLAY_LIGHT_TEXT_POS_X
#define DISPLAY_LIGHT_PROBAR_START_POS_Y    (DISPLAY_LIGHT_TEXT_POS_Y + 9)
#define DISPLAY_LIGHT_PROBAR_START_SIZE_X   1
#define DISPLAY_LIGHT_PROBAR_START_SIZE_Y   (DISPLAY_LIGHT_PROBAR_SIZE_Y + 2)
#define DISPLAY_LIGHT_PROBAR_STOP_POS_X     (DISPLAY_LIGHT_TEXT_POS_X + DISPLAY_LIGHT_PROBAR_MAX_SIZE_X +1)
#define DISPLAY_LIGHT_PROBAR_STOP_POS_Y     DISPLAY_LIGHT_PROBAR_START_POS_Y
#define DISPLAY_LIGHT_PROBAR_STOP_SIZE_X    1
#define DISPLAY_LIGHT_PROBAR_STOP_SIZE_Y    (DISPLAY_LIGHT_PROBAR_SIZE_Y + 2)
#define DISPLAY_LIGHT_PROBAR_POS_X          DISPLAY_LIGHT_TEXT_POS_X
#define DISPLAY_LIGHT_PROBAR_POS_Y          (DISPLAY_LIGHT_TEXT_POS_Y + 9)
#define DISPLAY_LIGHT_PROBAR_SIZE_Y         (4)
#define DISPLAY_LIGHT_PROBAR_MAX_SIZE_X     (6 * 6)

#endif /* CONF_APP_DISPLAY_H_INCLUDED */
