/**
 * \file
 *
 * \brief AVR XMEGA DMA example
 *
 * Copyright (c) 2010-2015 Atmel Corporation. All rights reserved.
 *
 * \asf_license_start
 *
 * \page License
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * 1. Redistributions of source code must retain the above copyright notice,
 *    this list of conditions and the following disclaimer.
 *
 * 2. Redistributions in binary form must reproduce the above copyright notice,
 *    this list of conditions and the following disclaimer in the documentation
 *    and/or other materials provided with the distribution.
 *
 * 3. The name of Atmel may not be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * 4. This software may only be redistributed and used in connection with an
 *    Atmel microcontroller product.
 *
 * THIS SOFTWARE IS PROVIDED BY ATMEL "AS IS" AND ANY EXPRESS OR IMPLIED
 * WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT ARE
 * EXPRESSLY AND SPECIFICALLY DISCLAIMED. IN NO EVENT SHALL ATMEL BE LIABLE FOR
 * ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
 * OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
 * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
 * STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * \asf_license_stop
 *
 */

/**
 * \mainpage
 *
 * \section intro Introduction
 * This simple example shows how to use the \ref dma_group.
 *
 * \section files Main Files
 * - dma_example.c example application
 * - conf_example.h example configuration
 *
 * \section device_info Device Info
 * All AVR XMEGA devices with a DMA controller can be used. This example have
 * been tested with the following setup:
 * - Xplain
 *
 * \section description Description of the example
 *
 * This example will start a DMA transfer between two internal memory areas,
 * and upon completion it will verify this by comparing those areas.
 *
 * During the progress of the application it will output some information to
 * the LEDS, and these LEDS have the following assignment:
 * - LED0: DMA have been started
 * - LED1: DMA completed successfully
 * - LED2: CPU verified DMA transfer to be correct
 * - LED3: CPU verified that source haven't been garbled
 * - LED5: DMA transfer ended in failure
 * - LED6: CPU verification of DMA transfer failed
 * - LED7: CPU verification of source failed
 *
 * In a successful operation LEDS 0, 1, 2 and 3 should light up in sequence,
 * and on fault LEDS 5, 6 and 7 will light up.
 *
 * \section dependencies Dependencies
 * This example depends on the following modules:
 * - \ref dma_group
 * - \ref gpio_group for LED output
 * - \ref pmic_group for interrupt handling
 *
 * \section compinfo Compilation info
 * This software was written for the GNU GCC and IAR for AVR. Other compilers
 * may or may not work.
 *
 * \section contactinfo Contact Information
 * For further information, visit <a href="http://www.atmel.com/">Atmel</a>.\n
 */
/*
 * Support and FAQ: visit <a href="http://www.atmel.com/design-support/">Atmel Support</a>
 */
#include <conf_example.h>
#include <string.h>
#include <asf.h>

/** \brief Source buffer to use for DMA transfer */
static uint8_t source[DMA_BUFFER_SIZE];

/** \brief Destination buffer to use for DMA transfer */
static uint8_t destination[DMA_BUFFER_SIZE];

/**
 * \brief Fill buffer with a specific pattern
 *
 * \param buffer Buffer to fill with a specific pattern
 * \param len Length of the buffer
 */
static void fill_pattern(uint8_t *buffer, size_t len)
{
	int i;

	for (i = 0; i < len; i++) {
		buffer[i] = 42 ^ (i & 0xff) ^ (i >> 8);
	}
}

/**
 * \brief Verify if buffer if filled by the specific pattern generated by the
 * fill_pattern() function.
 *
 * \param buffer Buffer to verify
 * \param len Length of the buffer
 *
 * \retval true Buffer is equal to specific pattern
 * \retval false Buffer is not equal to specific pattern
 */
static bool verify_pattern(uint8_t *buffer, size_t len)
{
	for (size_t i = 0; i < len; i++) {
		if (buffer[i] != (42 ^ (i & 0xff) ^ (i >> 8))) {
			return false;
		}
	}

	return true;
}

/**
 * \brief Callback for DMA transfer complete
 *
 * \param status Status of a completed (or failed) DMA transfer
 */
static void example_dma_transfer_done(enum dma_channel_status status)
{
	/* Check DMA transfer status */
	if (status == DMA_CH_TRANSFER_COMPLETED) {
		gpio_set_pin_low(LED1_GPIO);
	} else {
		gpio_set_pin_low(LED5_GPIO);
	}

	/* Check if destination is as expected */
	if (verify_pattern(destination, DMA_BUFFER_SIZE)) {
		gpio_set_pin_low(LED2_GPIO);
	} else {
		gpio_set_pin_low(LED6_GPIO);
	}

	/* Check if source haven't been garbled */
	if (verify_pattern(source, DMA_BUFFER_SIZE)) {
		gpio_set_pin_low(LED3_GPIO);
	} else {
		gpio_set_pin_low(LED7_GPIO);
	}
}

/**
 * \brief main function
 */
int main(void)
{
	struct dma_channel_config config;

	/*
	 * Initialize basic features for the AVR XMEGA family.
	 *  - PMIC is needed to enable all interrupt levels.
	 *  - Board init for setting up GPIO and board specific features.
	 *  - Sysclk init for configuring clock speed and turning of unused
	 *    peripherals.
	 *  - Sleepmgr init for setting up the basics for the sleep manager,
	 *    although not used in this example, but the sleep manager is used
	 *    by the DMA driver.
	 */
	pmic_init();
	board_init();
	sysclk_init();
	sleepmgr_init();

	/*
	 * Fill source buffer with a specific pattern and clear destination so
	 * we are sure they are different.
	 */
	fill_pattern(source, DMA_BUFFER_SIZE);
	memset(destination, 0, DMA_BUFFER_SIZE);

	dma_enable();

	/*
	 * In this example the example_dma_transfer_done() function will be
	 * used as the callback function from completed DMA block transfers.
	 * This function is called whenever an interrupt occurs on the DMA
	 * channel this function is set to handle. A callback function is set
	 * by the dma_set_callback() function in the DMA driver interface.
	 */
	dma_set_callback(DMA_CHANNEL, example_dma_transfer_done);

	/* Make sure config is all zeroed out so we don't get any stray bits */
	memset(&config, 0, sizeof(config));

	/*
	 * This example will configure a DMA channel with the following
	 * settings:
	 *  - Low interrupt priority
	 *  - 1 byte burst length
	 *  - DMA_BUFFER_SIZE bytes for each transfer
	 *  - Reload source and destination address at end of each transfer
	 *  - Increment source and destination address during transfer
	 *  - Source address is set to \ref source
	 *  - Destination address is set to \ref destination
	 */
	dma_channel_set_interrupt_level(&config, DMA_INT_LVL_LO);
	dma_channel_set_burst_length(&config, DMA_CH_BURSTLEN_1BYTE_gc);
	dma_channel_set_transfer_count(&config, DMA_BUFFER_SIZE);
	dma_channel_set_src_reload_mode(&config,
			DMA_CH_SRCRELOAD_TRANSACTION_gc);
	dma_channel_set_dest_reload_mode(&config,
			DMA_CH_DESTRELOAD_TRANSACTION_gc);
	dma_channel_set_src_dir_mode(&config, DMA_CH_SRCDIR_INC_gc);
	dma_channel_set_dest_dir_mode(&config, DMA_CH_DESTDIR_INC_gc);
	dma_channel_set_source_address(&config, (uint16_t)(uintptr_t)source);
	dma_channel_set_destination_address(&config,
			(uint16_t)(uintptr_t)destination);
	dma_channel_write_config(DMA_CHANNEL, &config);

	/* Use the configuration above by enabling the DMA channel in use. */
	dma_channel_enable(DMA_CHANNEL);

	/*
	 * Enable interrupts as the example is now configured to handle them
	 * properly.
	 */
	cpu_irq_enable();

	/*
	 * Trigger a manual start since there is no trigger sources used in
	 * this example.
	 */
	dma_channel_trigger_block_transfer(DMA_CHANNEL);

	/* Light the first LED to indicate that the DMA has started. */
	gpio_set_pin_low(LED0_GPIO);

	while (true) {
		/*
		 * Force a NOP instruction for an eventual placement of a debug
		 * session breakpoint.
		 */
		asm ("nop\n");
	}
}
