/**
 * \file
 *
 * \brief CRC example2 for AVR XMEGA
 *
 * Copyright (c) 2014-2018 Microchip Technology Inc. and its subsidiaries.
 *
 * \asf_license_start
 *
 * \page License
 *
 * Subject to your compliance with these terms, you may use Microchip
 * software and any derivatives exclusively with Microchip products.
 * It is your responsibility to comply with third party license terms applicable
 * to your use of third party software (including open source software) that
 * may accompany Microchip software.
 *
 * THIS SOFTWARE IS SUPPLIED BY MICROCHIP "AS IS". NO WARRANTIES,
 * WHETHER EXPRESS, IMPLIED OR STATUTORY, APPLY TO THIS SOFTWARE,
 * INCLUDING ANY IMPLIED WARRANTIES OF NON-INFRINGEMENT, MERCHANTABILITY,
 * AND FITNESS FOR A PARTICULAR PURPOSE. IN NO EVENT WILL MICROCHIP BE
 * LIABLE FOR ANY INDIRECT, SPECIAL, PUNITIVE, INCIDENTAL OR CONSEQUENTIAL
 * LOSS, DAMAGE, COST OR EXPENSE OF ANY KIND WHATSOEVER RELATED TO THE
 * SOFTWARE, HOWEVER CAUSED, EVEN IF MICROCHIP HAS BEEN ADVISED OF THE
 * POSSIBILITY OR THE DAMAGES ARE FORESEEABLE.  TO THE FULLEST EXTENT
 * ALLOWED BY LAW, MICROCHIP'S TOTAL LIABILITY ON ALL CLAIMS IN ANY WAY
 * RELATED TO THIS SOFTWARE WILL NOT EXCEED THE AMOUNT OF FEES, IF ANY,
 * THAT YOU HAVE PAID DIRECTLY TO MICROCHIP FOR THIS SOFTWARE.
 *
 * \asf_license_stop
 *
 */
/*
 * Support and FAQ: visit <a href="https://www.microchip.com/support/">Microchip Support</a>
 */
#include <asf.h>

 /**
 * \mainpage
 *
 * \section intro Introduction
 * This simple example shows how to use the \ref crc_group on FLASH memory.
 *
 * \section files Main Files
 * - crc.c CRC driver implementation
 * - crc.h CRC driver definitions
 * - example2.c example application
 *
 * \section device_info Device Info
 * All AVR XMEGA AU devices with a CRC module can be used. This example have
 * been tested with the following setup:
 * - XMEGA-A3BU Xplained
 *
 * \section description Description of the example
 * The example will setup the CRC module and generate CRC-32 for a range of
 * flash memory, then read the range of flash memory, append the calculated
 * checksum and use the I/O interface to calculate the checksum again to make
 * sure it is zero.
 * The example will then generate CRC for the boot section and the application
 * section and compare the checksum values with the checksums for the same
 * sections generated by flash range CRC.
 * For each successful CRC comparison, a message will be written to the screen.
 *
 * \section dependencies Dependencies
 * This example depends on the following modules:
 * - \ref crc_group
 * - \ref nvm_group
 * - \ref gfx_mono
 * - \ref gfx_mono_font
 *
 * \section compinfo Compilation info
 * This software was written for the GNU GCC. Other compilers
 * may or may not work.
 *
 * \section contactinfo Contact Information
 * For further information, visit <a href="http://www.microchip.com/">Microchip</a>.\n
 */
#define FLASHADDR 0x0300

/**
 * \brief Example 2 main application routine
 */
int main(void)
{
	uint8_t flashbuf[8];
	uint32_t checksum1;
	uint32_t checksum2;

	board_init();
	sysclk_init();
	gfx_mono_init();

	// Calculate checksum for an address range in flash.
	checksum1 = crc_flash_checksum(CRC_FLASH_RANGE, FLASHADDR, 4);

	// Read out the buffer from flash
	nvm_flash_read_buffer(FLASHADDR, flashbuf, 4);

	// Calculate checksum for the buffer from flash
	checksum2 = crc_io_checksum(flashbuf, 4, CRC_32BIT);

	// Make sure the calculated checksums are equal and write to screen
	if (checksum1 == checksum2) {
		gfx_mono_draw_string("Address range CRC OK",
				0, 0, &sysfont);
	}

	// Append the flash checksum and recalculate
	crc32_append_value(checksum1, flashbuf+4);
	checksum1 = crc_io_checksum(flashbuf, 8, CRC_32BIT);

	// Make sure the checksum is zero and write to screen
	if (checksum1 == 0) {
		gfx_mono_draw_string("IO CRC zero       OK", 0,
				SYSFONT_HEIGHT + 1, &sysfont);
	}

	// Calculate checksum for the boot section
	checksum1 = crc_flash_checksum(CRC_BOOT, 0, 0);

	// Recalculate checksum for the boot section using flash range CRC
	checksum2 = crc_flash_checksum(CRC_FLASH_RANGE, BOOT_SECTION_START,
			BOOT_SECTION_END-BOOT_SECTION_START+1);

	// Make sure the checksums are equal and write to screen
	if (checksum1 == checksum2) {
		gfx_mono_draw_string("Boot section CRC  OK",
				0, (SYSFONT_HEIGHT + 1)*2, &sysfont);
	}

	// Calculate checksum for the application section
	checksum1 = crc_flash_checksum(CRC_APP, 0, 0);

	// Recalculate checksum for the application section using flash range CRC
	checksum2 = crc_flash_checksum(CRC_FLASH_RANGE, APP_SECTION_START,
			APP_SECTION_END-APP_SECTION_START+1);
	// Make sure the checksums are equal and write to screen
	if (checksum1 == checksum2) {
		gfx_mono_draw_string("App section CRC   OK",
				0, (SYSFONT_HEIGHT + 1)*3, &sysfont);
	}

	// End of application, loop forever
	while (true) {
		// Intentionally left empty
	}

}
